Update tag.yml

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -26,11 +26,26 @@ jobs:
         
     - name: Bump Tag
       id: bump_tag
-      shell: bash
-      run: make bump_tag
-      env:
-        upgrade_level: ${{ inputs.upgrade_level }}
-
+      run: |
+        old_tag=$(git describe --tags --always $(git rev-list --tags --max-count=1)) | sed 's/v//'
+        case ${{ inputs.upgrade_level }} in
+          "patch")
+            incremented_version=$(echo $version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
+            ;;
+          "minor")
+            incremented_version=$(echo $version | awk -F. '{$(NF-1) = $(NF-1) + 1; $NF = 0 } 1' | sed 's/ /./g')
+            ;;
+          "major")
+            incremented_version=$(echo $version | awk -F. '{$(NF-2) = $(NF-2) + 1; $NF = 0; $(NF-1) = 0 } 1' | sed 's/ /./g')
+            ;;
+          *)
+            echo "Invalid upgrade level specified."
+            exit 1
+            ;;
+        esac
+        incremented_tag="v${incremented_version}"
+        echo "tag=${incremented_tag}" >> "$GITHUB_OUTPUT"
+        
   push_tag_name:
     runs-on: ubuntu-latest
     needs: bump_tag
