Update tag.yml

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -1,8 +1,22 @@
 name: Bump version
 on:
-  push:
-    branches:
-      - main
+  # push:
+  #   branches:
+  #     - main
+  # pull_request:
+  #   types: [closed]
+
+  workflow_dispatch:
+    inputs:
+      upgrade_level:
+        type: choice
+        description: kind of update
+        default: 'patch'
+        options: 
+        - patch
+        - minor
+        - major
+
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -35,14 +49,42 @@ jobs:
     - name: bump_tag
       id: bump_tag
       run: |
+        # old_tag=${{ needs.deploy.outputs.output1 }}
+        # echo $old_tag
+        # echo ${{ inputs.upgrade_level }} 
+        # version=$(echo $old_tag | sed 's/v//')
+        # incremented_version=$(echo $version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
+        # echo $incremented_version
+        # incremented_tag="v${incremented_version}"
+        # echo "tag=${incremented_tag}" >> "$GITHUB_OUTPUT"
+        ###########################################
         old_tag=${{ needs.deploy.outputs.output1 }}
         echo $old_tag
+        echo ${{ inputs.upgrade_level }} 
+    
+        # Extract version number without the 'v' prefix
         version=$(echo $old_tag | sed 's/v//')
-        incremented_version=$(echo $version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
-        echo $incremented_version
+    
+        # Increment the version based on the upgrade level
+        case ${{ inputs.upgrade_level }} in
+          "patch")
+            incremented_version=$(echo $version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
+            ;;
+          "minor")
+            incremented_version=$(echo $version | awk -F. '{$(NF-1) = $(NF-1) + 1; $NF = 0 } 1' | sed 's/ /./g')
+            ;;
+          "major")
+            incremented_version=$(echo $version | awk -F. '{$(NF-2) = $(NF-2) + 1; $NF = 0; $(NF-1) = 0 } 1' | sed 's/ /./g')
+            ;;
+          *)
+            echo "Invalid upgrade level specified."
+            exit 1
+            ;;
+        esac
+    
+        # Construct the new tag with the incremented version
         incremented_tag="v${incremented_version}"
         echo "tag=${incremented_tag}" >> "$GITHUB_OUTPUT"
-        
   push_tag_name:
     runs-on: ubuntu-latest
     needs: bump_tag
